-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '738353986140651a' HASH '269f9d74db3f62927a248861a1ba35ab39a046708dd656bde1cca86950ec8bae' ADMIN;         
DROP TABLE IF EXISTS "PUBLIC"."HTE_UTENTE" CASCADE;           
DROP TABLE IF EXISTS "PUBLIC"."UTENTE" CASCADE;               
DROP SEQUENCE IF EXISTS "PUBLIC"."UTENTE_SEQ";
CREATE SEQUENCE "PUBLIC"."UTENTE_SEQ" START WITH 1 INCREMENT BY 50;           
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_UTENTE"(
    "DATA_NASCITA" DATE,
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "CODICE_FISCALE" CHARACTER VARYING(255),
    "COGNOME" CHARACTER VARYING(255),
    "NOME" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."HTE_UTENTE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("RN_");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_UTENTE;              
CREATE MEMORY TABLE "PUBLIC"."UTENTE"(
    "ID" BIGINT NOT NULL,
    "CODICE_FISCALE" CHARACTER VARYING(255),
    "COGNOME" CHARACTER VARYING(255),
    "DATA_NASCITA" DATE,
    "NOME" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."UTENTE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_95" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.UTENTE;  
ALTER TABLE "PUBLIC"."UTENTE" ADD CONSTRAINT "PUBLIC"."UK3VD7DF1L1HNMHUKQ2BEMBT26N" UNIQUE NULLS DISTINCT ("CODICE_FISCALE"); 
